version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-operaciones
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME:-sig_operaciones}
      - DB_USER=${DB_USER:-siguser}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST:-restaurant-db}
      - DB_PORT=${DB_PORT:-3306}
      - REDIS_HOST=${REDIS_HOST:-redis-server}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    ports:
      - "8000:8000"
    command: daphne -b 0.0.0.0 -p 8000 operations_service.asgi:application --verbosity 2
    networks:
      - restaurant-network

networks:
  restaurant-network:
    external: true
    name: restaurant-network